
class Dealer
  @winner: bool
  @direction_name: String
  @top_card: Card
  
  def top_card=: -> Card
  def top_card: -> Card
  
  @player: Player
  @game_end: Time

  attr_accessor deck: Deck
  attr_accessor players: Array[Player]
  attr_accessor direction: Integer
  attr_accessor turn: Player
  attr_accessor current_player: Integer
  attr_accessor log: Logger
  attr_accessor total_players: Integer
  attr_accessor total_points: Complex | Float | Integer | Rational
  attr_accessor game_start: Time
  attr_accessor game_finish: Integer
  def initialize: (log: Logger, players: Array[String]) -> void

  def after_turn: -> Integer

  def before_turn: -> Integer

  def create_deck: -> Array[Card]

  def create_players: -> Array[Player]

  def deal_cards: -> Integer

  def draw_card: -> void

  def draw_four: -> Integer

  def draw_two: -> Integer

  def game_init: -> Array[Card]

  def increment_player: -> Integer
  def change_direction: -> String

  def initial_card_rules: -> Integer

  def log_after_turn: -> true

  def log_before_turn: -> true

  def play_game: -> Integer

  def points: -> (Integer)

  def reverse: -> true

  def set_defaults: -> Integer

  def skip: -> true

  def winner: -> Player
end
