
class Deck
  @log: Logger

  attr_accessor cards: Array[Card]
  def initialize: (Logger log, Integer number_of_decks) -> void
  def create_deck: (Integer number_of_decks) -> Range[Integer]
  def draw_card: -> nil
  def shuffle: -> Array[Card]
  def each_card: -> Card
  def length: -> Integer
end
