
class Player
  @total_points: Complex | Float | Integer | Rational

  attr_accessor name: String
  attr_accessor cards: Array[Card]
  attr_accessor dealer: Dealer
  attr_accessor type: String
  attr_accessor log: Logger
  attr_accessor color_playable: Array[Card]
  attr_accessor like_playable: Array[Card]
  def initialize: (log: Logger, name: String, dealer: Dealer) -> void
  def draw_card: (Integer num_cards) -> Integer
  def play_card: (Card top_card) -> nil
  def which_card: (Card top_card) -> nil
  def find_color_playable: (Card top_card) -> Array[Card]
  def find_like_playable: (Card top_card) -> Array[Card]
  def preferred_color: -> Integer
  def points: -> (Complex | Float | Integer | Rational)
  def to_s: -> String
end
